### ISSUE TITLE
Coocodo: изготовить

### ISSUE THREAD

**Issue by gusakovm** [milaxcom/Coocodo.app#1]
Изготовим, потом реп перенесу на bitbucket чтоб сделать приватным.

К сути:

---

Новое название: Coocodo.
Иконка приложения: http://bom.io/EaXE64qT.

Окошко в том же стиле, что Bonybom.

---

Верстка вся в репозитории. Там 2 страницы. К ним подключаются одни и те же js, css.
- [x] Title окна с WebView: "Coocodo WebView"
- [x] Title окна с параметрами: "Coocodo Get Client"

---

Coocodo WebView
- [x] Высота моего html: 225, ширина: 580. 
- [x] При загрузке окно НЕ ВОЗМОЖНО РЕСАЙЗИТЬ.
- [x] В поле инпута можно вводить урл и файл-урл (локальный)
- [x] Так же на окно можно кинуть html файл (дроп прямо в окно), при этом ссылку на файл надо передать функцией:

``` javascript
webview.url("http://...");
```
- [x] - После нажатия кнопки GO я передаю соответствующее событие в приложение. При этом вебвью меняем на новый вебвью с новой хтмлкой.
- [x] После того, как ссылку загрузили в вебвью — надо разрешить возможность ресайза окна во все стороны и под любой размер.
- [x] При ресайзе окна изменяется его размер. Он отображается вместе с кнопкой обновления в правом верхнем углу.
- [x] Иконка рефреша: http://bom.io/qNWrDj4P.
- [x] Выгдядит это все вот так: http://bom.io/gsSgd9lz.
- [x] Шрифт: хелветика ньюи, 10, #c9c9c9
- [x] Так же очень желательно организовать рефреш окна при нажатии сочитания CMD + R.
- [x] Реализовать chtml://refresh-coocodo — обновление окна.
- [ ] Сейчас постоянно трахает мозг кэш. Можно ли его как-то пофиксить? Чтоб вообще в этом вебвью отключать кэш?

---

Coocodo Get Client
- [x] Размер окна статичный (не ресайзится): w: 580px, h: 370px.
- [x] Суда просто надо передавать данные: 

```
get.add("?chtml://...");
```

---
- [x] По нажатию на иконку в доке: http://bom.io/0QnFQGWV. Туда надо добавить "Get Client", "WebView".
- [x] При этом, если WebView запущен и пользователь нажимает на пункт "WebView" ч/з иконку — старое окно уходит, появляется новое с инпутом для ввода url'а.

**Comment by mindesik** [comment]
> Размер окна статичный (не ресайзится): w: 580px, h: 370px.

Уточнить. Это точно размер окна? Или же webView?

**Comment by mindesik** [comment]
> В поле инпута можно вводить урл и файл-урл (локальный)

Мне кажется это в javascript пишется, потому-что инпут этот в html и доступа к нему у меня нет.

**Comment by gusakovm** [comment]
- [x] Окно webview должно ресайзиться под любой размер, без ограничений

**Comment by gusakovm** [comment]
- [ ] Копировать / вставить на хтмл инпуте
